### Add product to order
< {%
    request.variables.set("test_add_product", [ // test data
        {"id": "2", quantity: 2},
        {"id": "3", quantity: 3},
        {"id": "4", quantity: 20},
        {"id": "5", quantity: 5},
    ])
%}

POST http://localhost:8080/api/v1/order/add
Content-Type: application/x-www-form-urlencoded

productId = {{$.test_add_product..id}} &
quantity = {{$.test_add_product..quantity}}

### Get all product of current order
GET http://localhost:8080/api/v1/order/all

### Get total price of current order
GET http://localhost:8080/api/v1/order/total

### Palce Order
// Will remove all order cart in DB
POST http://localhost:8080/api/v1/order/place-order